apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker_image_deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker_image
  template:
    metadata:
      labels:
        app: docker_image
    spec:
      containers:
      - name: docker_image_container
        image: docker.io/panichella/tesi_mik:v1
        ports:
        - containerPort: 80