apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes_securityCheck_deployment
  labels:
    app: kubernetes_securityCheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes_securityCheck
  template:
    metadata:
      labels:
        app: kubernetes_securityCheck
    spec:
      containers:
      - name: kubernetes_securityCheck
        image: docker.io/panichella/tesi_mik:v1
        ports:
        - containerPort: 80