apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetessecurityCheckdeployment
  labels:
    app: kubernetessecurityCheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetessecurityCheck
  template:
    metadata:
      labels:
        app: kubernetes_securityCheck
    spec:
      containers:
      - name: kubernetessecurityCheck
        image: docker.io/panichella/tesi_mik:v1
        ports:
        - containerPort: 80