apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: docker.io/panichella/tesi_mik:v2
        ports:
        - containerPort: 5000
        env:
        - name: PYTHON_APP_SETTINGS
          value: production
        volumeMounts:
        - name: python-app-volume
          mountPath: /app
      volumes:
      - name: python-app-volume
        configMap:
          name: python-app-config