apiVersion: apps/v1
kind: Deployment
metadata:
  name: securitycheck-deployment
  labels:
    app: securitycheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securitycheck
  template:
    metadata:
      labels:
        app: securitycheck
    spec:
      containers:
      - name: securitycheck
        image: docker.io/panichella/tesi_mik:v2
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80